### ISSUE TITLE
[dcc64 Warning] UMMDBReader.pas(1398): W1035 Return value of function 'TMMDBReader.Find<T>' might be undefined

### ISSUE THREAD

**Issue by RoLex** [optinsoft/MMDBReader#4]
>function TMMDBReader.Find<T>(const ipAddress: TMMDBIPAddress; out prefixLength: Integer): T;
>var
>  pointer: Integer;
>begin
>  pointer := FindAddressInTree(ipAddress, prefixLength);
>  if pointer = 0 then Exit;
>  Result := ResolveDataPointer<T>(pointer);
>end;

Delphi 12, latest MMDBReader version.

**Comment by optinsoft** [comment]
Fixed in [commit](https://github.com/optinsoft/MMDBReader/commit/063590d26dc7d1674dc39250616b209c22d441d1). Now it raises EMMDBNotFoundException exception when ipAddress not found.

**Comment by RoLex** [comment]
Cool, thank you.
